version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    networks:
      - ssl_network
    restart: unless-stopped

networks:
  ssl_network:
    driver: bridge